/**
 * Liens internes contextuels — utilisés sur les piliers et pages filles premium
 * (objectif SEO : maillage dense, navigation utile).
 */
export const PREMIUM_INTERNAL_LINK_GRID: readonly { href: string; label: string }[] = [
  { href: '/sites-internet', label: 'Sites internet — vue d’ensemble' },
  { href: '/sites-internet/site-vitrine', label: 'Site vitrine' },
  { href: '/sites-internet/site-ecommerce', label: 'Site e-commerce' },
  { href: '/sites-internet/marketplace', label: 'Marketplace' },
  { href: '/sites-internet/site-mise-en-relation', label: 'Site de mise en relation' },
  { href: '/sites-internet/site-sur-mesure', label: 'Site sur mesure' },
  { href: '/sites-internet/site-wordpress', label: 'Site WordPress' },
  { href: '/sites-internet/intranet-extranet', label: 'Intranet / extranet' },
  { href: '/sites-internet/landing-page', label: 'Landing page' },
  { href: '/applications-mobiles', label: 'Applications mobiles — vue d’ensemble' },
  { href: '/applications-mobiles/ios', label: 'Développement iOS' },
  { href: '/applications-mobiles/android', label: 'Développement Android' },
  { href: '/applications-mobiles/react-native', label: 'React Native' },
  { href: '/applications-mobiles/pwa', label: 'PWA' },
  { href: '/ia', label: 'Intelligence artificielle — vue d’ensemble' },
  { href: '/ia/integration-ia', label: 'IA dans le site ou l’appli' },
  { href: '/ia/chatbot-ia', label: 'Chatbot & assistant' },
  { href: '/ia/agents-ia', label: 'Agents & scénarios multi-étapes' },
  { href: '/ia/automatisation-ia', label: 'Automatisation IA' },
  { href: '/ia/rag-base-connaissances', label: 'RAG & base de connaissances' },
  { href: '/ia/ia-generative-ecommerce', label: 'IA & e-commerce' },
  { href: '/seo', label: 'SEO & GEO — vue d’ensemble' },
  { href: '/seo/audit-seo', label: 'Audit SEO' },
  { href: '/seo/seo-technique', label: 'SEO technique' },
  { href: '/seo/seo-local', label: 'SEO local' },
  { href: '/seo/seo-ecommerce', label: 'SEO e-commerce' },
  { href: '/seo/migration-seo', label: 'Migration SEO' },
  { href: '/seo/redaction-seo', label: 'Rédaction SEO' },
  { href: '/seo/netlinking', label: 'Netlinking' },
  { href: '/seo/geo-generative-engine-optimization', label: 'GEO (visibilité dans les IA)' },
  { href: '/crm-outils-metiers', label: 'CRM & outils métiers — vue d’ensemble' },
  { href: '/crm-outils-metiers/crm-sur-mesure', label: 'CRM sur mesure' },
  { href: '/crm-outils-metiers/integration-crm', label: 'Intégration CRM' },
  { href: '/crm-outils-metiers/automatisation', label: 'Automatisation métier' },
  { href: '/maintenance', label: 'Maintenance web' },
  { href: '/realisations', label: 'Réalisations' },
  { href: '/a-propos', label: 'À propos' },
  { href: '/contact', label: 'Contact' },
  { href: '/devis', label: 'Demander un devis' },
  { href: '/blog', label: 'Blog' },
] as const;
